
const APP_NAME = 'طشّة';
const APP_TAGLINE = 'تحت إشراف م. مالك';
const I18N = {
  ar:{home:'الرئيسية',properties:'العقارات',bookings:'الحجوزات',owner:'المالك',admin:'الإدارة',login:'الدخول',favorites:'المفضلة',myBookings:'حجوزاتي',install:'تثبيت',later:'لاحقًا'},
  en:{home:'Home',properties:'Properties',bookings:'Bookings',owner:'Owner',admin:'Admin',login:'Login',favorites:'Favorites',myBookings:'My Bookings',install:'Install',later:'Later'}
};
function qs(s){return document.querySelector(s)} function qsa(s){return [...document.querySelectorAll(s)]}
function tr(k){const lang=getLang(); return (I18N[lang]&&I18N[lang][k])||I18N.ar[k]||k}
function setupMobileNav(){ const btn=qs('#mobileToggle'), nav=qs('#mainNav'); if(btn&&nav) btn.onclick=()=>nav.classList.toggle('open'); }
function applyLocale(){ document.documentElement.lang=getLang()==='en'?'en':'ar'; document.documentElement.dir=getLang()==='en'?'ltr':'rtl'; document.body.classList.toggle('lang-en', getLang()==='en'); }
function updateCounters(){ qsa('[data-favorites-count]').forEach(n=>n.textContent=getFavorites().length); qsa('[data-bookings-count]').forEach(n=>n.textContent=getBookings().length); qsa('[data-users-count]').forEach(n=>n.textContent=getUsers().length); }
function highlightCurrentNav(){ const path=location.pathname.split('/').pop()||'index.html'; qsa('[data-nav],[data-mobile-nav]').forEach(a=>{ if(a.getAttribute('href')===path) a.classList.add('active');}); }
function renderHeader(){ const el=qs('[data-site-header]'); if(!el) return; el.innerHTML=`<div class="container nav-wrap"><a class="brand" href="index.html"><div class="logo-mark"><img src="assets/logo.png" alt="شعار طشة"></div><div class="brand-copy"><strong>${APP_NAME} | TASHA</strong><small>${APP_TAGLINE}</small></div></a><button class="mobile-toggle btn btn-secondary btn-small" id="mobileToggle">☰</button><nav class="nav" id="mainNav"><a href="index.html" data-nav>${tr('home')}</a><a href="properties.html" data-nav>${tr('properties')}</a><a href="bookings.html" data-nav>${tr('bookings')}</a><a href="owner-dashboard.html" data-nav>${tr('owner')}</a><a href="admin-dashboard.html" data-nav>${tr('admin')}</a><a href="login.html" data-nav>${tr('login')}</a></nav><div class="nav-tools"><div class="toolbar-switches"><button id="langToggle" class="btn btn-secondary btn-small">${getLang()==='ar'?'EN':'AR'}</button><button id="currencyToggle" class="btn btn-secondary btn-small">${getCurrency()}</button></div><a href="properties.html" class="btn btn-secondary btn-small">${tr('favorites')} <span data-favorites-count>0</span></a><a href="bookings.html" class="btn btn-primary btn-small">${tr('myBookings')} <span data-bookings-count>0</span></a></div></div>`; qs('#langToggle')?.addEventListener('click',()=>{setLang(getLang()==='ar'?'en':'ar'); location.reload()}); qs('#currencyToggle')?.addEventListener('click',()=>{setCurrency(getCurrency()==='JOD'?'USD':'JOD'); location.reload()}); }
function renderFooter(){ const el=qs('[data-site-footer]'); if(!el) return; el.innerHTML=`<div class="container footer-grid"><div><div class="brand" style="margin-bottom:12px"><div class="logo-mark"><img src="assets/logo.png" alt="شعار طشة"></div><div class="brand-copy"><strong style="color:#fff">${APP_NAME} | TASHA</strong><small>${APP_TAGLINE}</small></div></div><p>منصة عربية لحجز المزارع والشاليهات والفلل والشقق الفندقية داخل الأردن، مع اقتراحات ذكية، دفع، وسند حجز PDF.</p></div><div><h4>روابط سريعة</h4><ul><li><a href="properties.html">${tr('properties')}</a></li><li><a href="bookings.html">${tr('bookings')}</a></li><li><a href="owner-dashboard.html">${tr('owner')}</a></li><li><a href="admin-dashboard.html">${tr('admin')}</a></li></ul></div><div><h4>التواصل</h4><ul><li>عمّان، الأردن</li><li>hello@tasha.jo</li><li>079 000 0000</li><li>متاح يوميًا 9 صباحًا - 10 مساءً</li></ul></div></div>`; }
function renderMobileAppNav(){ if(qs('.mobile-app-nav')) return; const nav=document.createElement('nav'); nav.className='mobile-app-nav'; nav.innerHTML=`<a href="index.html" data-mobile-nav>🏠<span>${tr('home')}</span></a><a href="properties.html" data-mobile-nav>🔎<span>${tr('properties')}</span></a><a href="bookings.html" data-mobile-nav>📄<span>${tr('bookings')}</span></a><a href="owner-dashboard.html" data-mobile-nav>🏡<span>${tr('owner')}</span></a><a href="login.html" data-mobile-nav>👤<span>${tr('login')}</span></a>`; document.body.appendChild(nav); }
function renderPropertyCard(item){ const fav=getFavorites().includes(item.id); return `<article class="card"><div class="card-image-wrap"><img class="card-image" src="${item.image}" alt="${item.name}"><div class="badge-row"><span class="badge">${item.type}</span>${item.offer?'<span class="badge accent">عرض خاص</span>':''}</div></div><div class="card-body"><div class="card-title-row"><div><h3>${item.name}</h3><div class="card-city">${item.city}</div></div><div class="price">${formatCurrency(item.price)}</div></div><div class="meta-list"><span class="meta-item">${item.guests} guests</span><span class="meta-item">⭐ ${item.rating}</span><span class="meta-item">${item.pool?'مسبح خاص':'جلسة خارجية'}</span></div><p class="card-desc">${item.description}</p><div class="card-actions"><a class="btn btn-primary" href="property.html?id=${item.id}">عرض التفاصيل</a><button class="btn btn-secondary" data-favorite="${item.id}">${fav?'إزالة من المفضلة':'إضافة للمفضلة'}</button></div></div></article>`; }
function bindFavoriteButtons(scope=document){ scope.querySelectorAll('[data-favorite]').forEach(btn=>btn.addEventListener('click',()=>{toggleFavorite(Number(btn.dataset.favorite)); updateCounters(); location.reload();})); }
function renderRecommendationCards(result){ return `<div class="chat-bubble ai"><h4>${result.title}</h4><p>${result.summary}</p><div class="dashboard-grid" style="margin-top:12px">${result.matches.map(item=>`<div class="panel"><div class="row-between"><strong>${item.name}</strong><span class="price">${formatCurrency(item.price)}</span></div><div class="meta-list"><span class="meta-item">${item.city}</span><span class="meta-item">${item.type}</span></div><ul>${item.reason.map(r=>`<li>${r}</li>`).join('')}</ul><a class="btn btn-secondary btn-small" href="property.html?id=${item.id}">عرض التفاصيل</a></div>`).join('')}</div><div class="chat-actions">${result.tips.map(t=>`<span class="status-chip">${t}</span>`).join('')}</div></div>` }
function setupAiChat(opts={}){ const promptEl=qs(opts.promptSelector||'#aiPrompt'); const resultEl=qs(opts.resultSelector||'#aiResult'); const btn=qs(opts.buttonSelector||'#runAiBtn'); if(!promptEl||!resultEl||!btn) return; qsa(opts.chipsSelector||'.sample-chip').forEach(ch=>ch.addEventListener('click',()=>promptEl.value=ch.textContent.trim())); const run=()=>{ const prompt=promptEl.value.trim(); if(!prompt) return; resultEl.innerHTML += `<div class="chat-bubble user">${prompt}</div>`; const res=runAiRecommendation(prompt); resultEl.innerHTML += renderRecommendationCards(res); resultEl.scrollTop=resultEl.scrollHeight; saveConversation({prompt, result:res}); promptEl.value=''; }; btn.addEventListener('click',run); promptEl.addEventListener('keydown',e=>{ if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run();}}); }
let deferredPrompt=null; function setupInstallPrompt(){ const banner=document.createElement('div'); banner.className='install-banner'; banner.innerHTML=`<div class="row-between"><div><strong>إضافة الموقع إلى الشاشة الرئيسية</strong><p style="margin:6px 0 0;color:var(--muted)">يمكن تثبيته على الهاتف للوصول السريع من الشاشة الرئيسية.</p></div><div class="card-actions"><button id="installBtn" class="btn btn-primary btn-small">${tr('install')}</button><button id="dismissInstall" class="btn btn-secondary btn-small">${tr('later')}</button></div></div>`; document.body.appendChild(banner); window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;banner.classList.add('show')}); banner.addEventListener('click',async e=>{ if(e.target.id==='dismissInstall') banner.classList.remove('show'); if(e.target.id==='installBtn'&&deferredPrompt){ deferredPrompt.prompt(); await deferredPrompt.userChoice; banner.classList.remove('show'); deferredPrompt=null; }}); }
function registerServiceWorker(){ if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{}) }
window.addEventListener('DOMContentLoaded',()=>{ applyLocale(); renderHeader(); renderFooter(); renderMobileAppNav(); setupMobileNav(); updateCounters(); highlightCurrentNav(); setupInstallPrompt(); registerServiceWorker(); });
